*  DSC530 Data Exploration and Analysis
*  Weeks 5 & 6 Coding Assignment
*  Peter Lozano

# Chapter 4 Exercises

## Exercise 1.
With the `earthquakes.csv` file, select all the earthquakes in Japan with a magnitude of 4.9 or greater using the `mb` magnitude type.

Importing necessary packages

In [13]:
import pandas as pd
import numpy as np

Reading necessary csv's to complete Assignment

In [ ]:
# Reading both earthquakes and faang csv files
quakes = pd.read_csv('../../ch_04/exercises/earthquakes.csv')
faang = pd.read_csv('../../ch_04/exercises/faang.csv', index_col='date', parse_dates=True)
quakes.head()

    mag magType           time                  place  tsunami parsed_place
0  1.35      ml  1539475168010  9km NE of Aguanga, CA        0   California
1  1.29      ml  1539475129610  9km NE of Aguanga, CA        0   California
2  3.42      ml  1539475062610  8km NE of Aguanga, CA        0   California
3  0.44      ml  1539474978070  9km NE of Aguanga, CA        0   California
4  2.16      md  1539474716050  10km NW of Avenal, CA        0   California

In [16]:
# We will filter the quakes dataframe for earthquakes in Japan with a magnitude of 4.9 or greater using the 'mb' magnitude type.
japan_quakes = quakes[(quakes['place'].str.contains('Japan')) &
                      (quakes['mag'] >= 4.9) &
                      (quakes['magType'] == 'mb')
                      ]
japan_quakes

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

# Exercise 2

Create bins for each full number of magnitude (*for example, the first bin is (0,1), the second is (1, 2), and so on*) with the `ml` magnitude type and count how many are in each bin.

In [20]:
# Create bins of size 1 for the magnitude
mag_bins = np.arange(0,
                     quakes.loc[quakes['magType'] == 'ml']\
                         .mag.max() + 1
)

# Create a cross-tabulation of magnitude bins and magnitude types
binned_magnitudes = pd.crosstab(
    pd.cut(
        quakes.mag,
        bins=mag_bins
    ),
    quakes.magType
)

# Display only the 'ml' column
print(binned_magnitudes['ml'])

mag
(0.0, 1.0]    2207
(1.0, 2.0]    3105
(2.0, 3.0]     862
(3.0, 4.0]     122
(4.0, 5.0]       2
(5.0, 6.0]       1
Name: ml, dtype: int64

# Exercise 3

Using the `exercises/faang.csv` file, group by the ticker and resample to monthly frequency.

Aggregate the:

open and close prices with the **mean**,

the high price with the **max**,

the low price with the **min**,

and the **volume** with the sum.

In [ ]:
# Display the first few rows of every ticker's resampled data
faang.groupby('ticker').resample('ME').agg(
    {
        'open': 'mean',
        'high': 'max',
        'low': 'min',
        'close': 'mean',
        'volume': 'sum'
    }
)

# Alternatively, we can print the first few data points grouped by ticker
# for ticker, data in faang.groupby('ticker'):
#     print(f"Ticker: {ticker}")
#     print(data.resample('ME').agg(
#         {
#             'open': 'mean',
#             'high': 'max',
#             'low': 'min',
#             'close': 'mean',
#             'volume': 'sum'
#         }
#     ).head())

                          open         high          low        close  \
ticker date
AAPL   2018-01-31    43.505357    45.025002    41.174999    43.501309
       2018-02-28    41.819079    45.154999    37.560001    41.909737
       2018-03-31    43.761786    45.875000    41.235001    43.624048
       2018-04-30    42.441310    44.735001    40.157501    42.458572
       2018-05-31    46.239091    47.592499    41.317501    46.384205
       2018-06-30    47.180119    48.549999    45.182499    47.155357
       2018-07-31    47.549048    48.990002    45.855000    47.577857
       2018-08-31    53.121739    57.217499    49.327499    53.336522
       2018-09-30    55.582763    57.417500    53.825001    55.518421
       2018-10-31    55.300000    58.367500    51.522499    55.211413
       2018-11-30    47.954881    55.590000    42.564999    47.808929
       2018-12-31    41.310789    46.235001    36.647499    41.066579
AMZN   2018-01-31  1301.377151  1472.579956  1170.510010  1309.010946
       2018-02-28  1447.113159  1528.699951  1265.930054  1442.363146
       2018-03-31  1542.160464  1617.540039  1365.199951  1540.367629
       2018-04-30  1475.841902  1638.099976  1352.880005  1468.220471
       2018-05-31  1590.474543  1635.000000  1546.020020  1594.903637
       2018-06-30  1699.088582  1763.099976  1635.089966  1698.823812
       2018-07-31  1786.305716  1880.050049  1678.060059  1784.649042
       2018-08-31  1891.957833  2025.569946  1776.020020  1897.851308
       2018-09-30  1969.239476  2050.500000  1865.000000  1966.077900
       2018-10-31  1799.630865  2033.189941  1476.359985  1782.058265
       2018-11-30  1622.323806  1784.000000  1420.000000  1625.483823
       2018-12-31  1572.922100  1778.339966  1307.000000  1559.443154
FB     2018-01-31   184.584284   190.660004   175.800003   184.962856
       2018-02-28   180.721578   195.320007   167.179993   180.269473
       2018-03-31   173.449524   186.100006   149.020004   173.489522
       2018-04-30   164.163332   177.100006   150.509995   163.810476
       2018-05-31   181.910909   192.720001   170.229996   182.930000
       2018-06-30   194.974763   203.550003   186.429993   195.267620
       2018-07-31   199.332381   218.619995   166.559998   199.967142
       2018-08-31   177.598695   188.300003   170.270004   177.492172
       2018-09-30   164.233158   173.889999   158.869995   164.377368
       2018-10-31   154.873479   165.880005   139.029999   154.187826
       2018-11-30   141.762857   154.130005   126.849998   141.635715
       2018-12-31   137.529475   147.190002   123.019997   137.161052
GOOG   2018-01-31  1127.200945  1186.890015  1045.229980  1130.770467
       2018-02-28  1088.629472  1174.000000   992.559998  1088.206839
       2018-03-31  1096.108085  1177.050049   980.640015  1091.490479
       2018-04-30  1038.415237  1094.165039   990.369995  1035.696187
       2018-05-31  1064.021376  1110.750000  1006.289978  1069.275901
       2018-06-30  1136.396182  1186.286011  1096.010010  1137.626668
       2018-07-31  1183.464280  1273.890015  1093.800049  1187.590472
       2018-08-31  1226.156951  1256.500000  1188.239990  1225.671732
       2018-09-30  1176.878424  1212.989990  1146.910034  1175.808934
       2018-10-31  1116.082172  1209.959961   995.830017  1110.940411
       2018-11-30  1054.971424  1095.569946   996.020020  1056.162394
       2018-12-31  1042.619998  1124.650024   970.109985  1037.420519
NFLX   2018-01-31   231.269525   286.809998   195.419998   232.908096
       2018-02-28   270.873158   297.359985   236.110001   271.443683
       2018-03-31   312.712859   333.980011   275.899994   312.228097
       2018-04-30   309.129524   338.820007   271.220001   307.466192
       2018-05-31   329.779541   356.100006   305.730011   331.536819
       2018-06-30   384.557143   423.209991   352.820007   384.133336
       2018-07-31   380.969526   419.769989   328.000000   381.515238
       2018-08-31   345.410001   376.809998   310.929993   346.257824
       2018-09-30   363.326843   383.200012   335.829987   362.641576
       2018-10-31   340.025218   386.799988   271.209991   335.445652
       2018-11-30   290.643335   332.049988   250.000000   290.344764
       2018-12-31   266.309474   298.720001   231.229996   265.302630

                         volume
ticker date
AAPL   2018-01-31  2.638718e+09
       2018-02-28  3.711577e+09
       2018-03-31  2.854911e+09
       2018-04-30  2.664617e+09
       2018-05-31  2.483905e+09
       2018-06-30  2.110498e+09
       2018-07-31  1.574766e+09
       2018-08-31  2.801276e+09
       2018-09-30  2.715888e+09
       2018-10-31  3.158994e+09
       2018-11-30  3.845306e+09
       2018-12-31  3.595690e+09
AMZN   2018-01-31  9.637120e+07
       2018-02-28  1.377840e+08
       2018-03-31  1.304001e+08
       2018-04-30  1.299196e+08
       2018-05-31  7.161550e+07
       2018-06-30  8.594130e+07
       2018-07-31  9.752110e+07
       2018-08-31  9.657580e+07
       2018-09-30  9.444550e+07
       2018-10-31  1.832208e+08
       2018-11-30  1.392900e+08
       2018-12-31  1.548127e+08
FB     2018-01-31  4.956557e+08
       2018-02-28  5.162516e+08
       2018-03-31  9.962017e+08
       2018-04-30  7.500727e+08
       2018-05-31  4.011441e+08
       2018-06-30  3.872656e+08
       2018-07-31  6.470307e+08
       2018-08-31  5.488327e+08
       2018-09-30  5.004688e+08
       2018-10-31  6.224463e+08
       2018-11-30  5.181517e+08
       2018-12-31  5.587862e+08
GOOG   2018-01-31  2.873840e+07
       2018-02-28  4.238200e+07
       2018-03-31  4.535330e+07
       2018-04-30  4.171590e+07
       2018-05-31  3.184940e+07
       2018-06-30  3.209600e+07
       2018-07-31  3.194010e+07
       2018-08-31  2.880840e+07
       2018-09-30  2.886240e+07
       2018-10-31  4.849470e+07
       2018-11-30  3.673510e+07
       2018-12-31  4.025760e+07
NFLX   2018-01-31  2.383776e+08
       2018-02-28  1.845858e+08
       2018-03-31  2.634494e+08
       2018-04-30  2.620060e+08
       2018-05-31  1.420508e+08
       2018-06-30  2.440318e+08
       2018-07-31  3.053938e+08
       2018-08-31  2.131223e+08
       2018-09-30  1.708321e+08
       2018-10-31  3.635898e+08
       2018-11-30  2.571264e+08
       2018-12-31  2.343100e+08

# Exercise 4

Build a crosstab with the earthquake data between the `tsunami` column and the `magType` column.

Rather than showing the frequency count, show the **maximum magnitude** that was observed for *each* combination. 

Put the magnitude type along the columns.

In [ ]:
pd.crosstab(quakes.tsunami,
            quakes.magType,
            values=quakes.mag,
            aggfunc='max'
)

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

# Exercise 5

Calculate the rolling 60-day aggregations of the OHLC data by ticker for the FAANG data. Use the same aggregations as exercise 3.

In [ ]:
# Adding rolling 60-day aggregations of the OHLC data by ticker for the FAANG data. Use the same aggregations as exercise 3.
faang.groupby('ticker').rolling('60D').agg(
    {
        'open': 'mean',
        'high': 'max',
        'low': 'min',
        'close': 'mean',
        'volume': 'sum'
    }
)

                         open        high         low       close       volume
ticker date
AAPL   2018-01-02   42.540001   43.075001   42.314999   43.064999  102223600.0
       2018-01-03   42.836250   43.637501   42.314999   43.061249  220295200.0
       2018-01-04   42.935833   43.637501   42.314999   43.126666  310033600.0
       2018-01-05   43.041875   43.842499   42.314999   43.282499  404673600.0
       2018-01-08   43.151000   43.902500   42.314999   43.343500  486944800.0
...                       ...         ...         ...         ...          ...
NFLX   2018-12-24  283.509251  332.049988  233.679993  281.931750  525657600.0
       2018-12-26  281.844501  332.049988  231.229996  280.777750  520444300.0
       2018-12-27  281.070489  332.049988  231.229996  280.162927  532679500.0
       2018-12-28  279.916342  332.049988  231.229996  279.461464  521973500.0
       2018-12-31  278.430770  332.049988  231.229996  277.451539  476314900.0

[1255 rows x 5 columns]

# Exercise 6

Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [34]:
faang.pivot_table(index='ticker')

              close         high          low         open        volume
ticker
AAPL      47.263357    47.748526    46.795877    47.277859  1.360803e+08
AMZN    1641.726176  1662.839839  1619.840519  1644.072709  5.648994e+06
FB       171.510956   173.613347   169.303148   171.472948  2.765860e+07
GOOG    1113.225134  1125.777606  1101.001658  1113.554101  1.741965e+06
NFLX     319.290319   325.219322   313.187330   319.620558  1.146962e+07

# Exercise 7

Calculate the Z-scores of Amazon's data (ticker: AMZN) in Q4 2018 using apply().

In [49]:
# Indexing the dataset
faang[
    (faang.index.quarter == 4) &
    (faang.index.year == 2018) &
    (faang['ticker'] == 'AMZN')
].drop(columns = 'ticker').apply(
    lambda x: x.sub(x.mean()).div(x.std())
).head()

                high       low      open     close    volume
date
2018-10-01  2.368006  2.502113  2.337813  2.385848 -1.630411
2018-10-02  2.227302  2.247433  2.190795  2.155037 -0.861879
2018-10-03  2.058955  2.139987  2.068570  2.025489 -0.920345
2018-10-04  1.819474  1.781561  1.850048  1.722816 -0.126582
2018-10-05  1.628173  1.554416  1.642819  1.584748 -0.298771

# Exercise 10

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called 

daily number of new reported cases of COVID-19 by country worldwide. 

This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. 

Complete the following tasks to practice the skills you've learned up to this point in the book:

## Part 1

1. Read in the data in the `exercises/covid19_cases.csv` file
2. Create a `date` column by parsing the `dateRep` column into a datetime
3. Set the `date` column as the index
4. Use the `replace()` method to update all occurrences of `United_States_of_America` and `United Kingdom` to `USA` and `UK`, respectively
5. Sort the index

In [ ]:
# Assigning a date column by parsing the dateRep column into a datetime
# Setting the date column as the index
# Replacing long country names with their abbreviations
# Sorting the index
covid = pd.read_csv('../../ch_04/exercises/covid19_cases.csv')\
    .assign(date=lambda x: pd.to_datetime(x.dateRep, format='%d/%m/%Y'))\
    .set_index('date')\
    .replace('United_States_of_America', 'USA')\
    .replace('United_Kingdom', 'UK')\
    .sort_index()

## Part 2

For the 5 countries with the most cases (cumulative), find the day with the largest number of cases.

In [59]:
# Creating a list of the top five countries with the most cumulative cases
top_five_countries = covid\
    .groupby('countriesAndTerritories').cases.sum()\
    .nlargest(5).index

# Indexing the covid dataframe for only the top five countries
# Finding the day with the largest number of cases for each of those countries
covid[covid.countriesAndTerritories.isin(top_five_countries)]\
    .groupby('countriesAndTerritories').cases.idxmax()

countriesAndTerritories
Brazil   2020-07-30
India    2020-09-17
Peru     2020-08-17
Russia   2020-07-18
USA      2020-07-25
Name: cases, dtype: datetime64[ns]

# Part 3

Find the 7-day average change in COVID-19 cases for the last week in the data for the countries found in Part 2.

In [ ]:
# Start with the 7-day rolling average of daily changes in cases for each country
rolling_avg = covid\
    .groupby(['countriesAndTerritories', pd.Grouper(freq='1D')]).cases.sum()\
    .unstack(0).diff().rolling(7).mean()

# Get the last date in the dataset
last_date = rolling_avg.index.max()

# Calculate the start date for the last 7 days
start_date = last_date - pd.Timedelta(days=6)

# Create a mask for the last 7 days
mask = (rolling_avg.index >= start_date) & (rolling_avg.index <= last_date)

# Apply the mask to get the results
result = rolling_avg.loc[mask, top_five_countries]
result

countriesAndTerritories,USA,India,Brazil,Russia,Peru
date,,,,,
2020-09-13,-474.285714,534.285714,479.285714,40.428571,-98.857143
2020-09-14,473.714286,181.285714,35.285714,36.285714,73.142857
2020-09-15,1513.000000,1142.857143,697.428571,46.285714,377.571429
2020-09-16,3478.714286,59.571429,3196.285714,61.428571,-65.000000
2020-09-17,-1047.000000,308.428571,143.428571,810.000000,-29.428571
2020-09-18,865.714286,-18.142857,-607.714286,-688.428571,-227.571429
2020-09-19,306.857143,-604.714286,-560.142857,57.285714,-41.285714

# Part 4

Find the first date that each country other than China had cases.

In [62]:
# Using pivot to find the first date that each country other than China had cases
covid\
    .pivot(columns='countriesAndTerritories', values='cases')\
    .drop(columns='China')\
    .apply(lambda x: x[x > 0].index.min())\
    .sort_values()\
    .rename(lambda x: x.replace('_', ' '))

countriesAndTerritories
Thailand         2020-01-13
Japan            2020-01-15
South Korea      2020-01-20
Taiwan           2020-01-21
USA              2020-01-21
                    ...
Yemen            2020-04-10
Western Sahara   2020-04-26
Tajikistan       2020-05-01
Comoros          2020-05-02
Lesotho          2020-05-15
Length: 209, dtype: datetime64[ns]

# Part 5

Rank the countries by total cases using percentiles.

In [ ]:
# Within the transform method, we will use rank with method='max' and pct=True to get the percentile rank of each country by total cases.
covid\
    .pivot_table(columns='countriesAndTerritories', values='cases', aggfunc='sum')\
    .T\
    .transform('rank', method='max', pct=True)\
    .sort_values('cases', ascending=False)\
    .rename(lambda x: x.replace('_', ' '))

                                cases
countriesAndTerritories
USA                          1.000000
India                        0.995238
Brazil                       0.990476
Russia                       0.985714
Peru                         0.980952
...                               ...
Greenland                    0.023810
Montserrat                   0.019048
Falkland Islands (Malvinas)  0.019048
Holy See                     0.009524
Anguilla                     0.004762

[210 rows x 1 columns]